FROM python:3.9

ENV FLASK_APP=app

WORKDIR /usr/app/server

COPY server/requirements.txt .

RUN pip install -r requirements.txt
RUN pip install psycopg2

COPY server .

EXPOSE 5000

CMD ["gunicorn", "-b", ":5000", "app:app"]