FROM node:16.19.0-alpine AS build-stage

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/app/client

COPY client/package*.json .

RUN npm install && npm cache clean --force

COPY client .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build-stage /usr/app/client/build /usr/share/nginx/html

COPY client/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]